### ISSUE TITLE
it can't be the fastest sniper

### ISSUE THREAD

**Issue by mewzax** [Automized/Tsukuyomi-Nitro-Sniper#1]
why using net/http as http client

**Comment by VichyGopher** [comment]
because gay can't handle raw socket

**Comment by mewzax** [comment]
> because gay can't handle raw socket

j avais ouvert une ptite PR pour les aider XD:
https://github.com/Automized/Tsukuyomi-Nitro-Sniper/pull/2/commits/e0947330e9e7edcca9489790feb5328ecb927caa
